lib: edge_impulse: Disable FP16 option in samples and apps
THe CMSIS DSP provided with edge impulse library does not seem to be
compatible with recently introduced Zephyr CONFIG_FP16 option, it ends
up in a compilation error:

error: conflicting types for 'float_t'

Disable the CONFIG_FP16 option in samples/apps using edge impulse.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>